import { NextResponse } from "next/server";
import { cleanText, crmErrorResponse, isUuid, requireTalentCrmRequester } from "@/lib/crm/server";

const TYPES = new Set(["hiring_manager", "recruiter", "department_head", "executive", "other"]);
const SELECT = "id,employer_user_id,full_name,work_email,phone,job_title,department,contact_type,status,notes,created_at,updated_at";

export async function GET(request: Request) {
  try { const context = await requireTalentCrmRequester(request); if ("response" in context) return context.response; const url = new URL(request.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1)); const limit = Math.max(1, Math.min(100, Number(url.searchParams.get("limit") || 25))); const from = (page - 1) * limit; let query = context.client.from("employer_contacts").select(SELECT, { count: "exact" }).eq("employer_user_id", context.workspaceOwnerId); const status = url.searchParams.get("status"); if (status === "active" || status === "inactive") query = query.eq("status", status); const result = await query.order("updated_at", { ascending: false }).range(from, from + limit - 1); if (result.error) throw result.error; const contactIds = (result.data || []).map((row) => row.id); const logs = contactIds.length ? await context.client.from("communication_logs").select("id,contact_id,channel,direction,subject,summary,occurred_at").in("contact_id", contactIds).order("occurred_at", { ascending: false }).limit(250) : { data: [], error: null }; if (logs.error) throw logs.error; return NextResponse.json({ contacts: result.data || [], communicationHistory: logs.data || [], page, limit, total: result.count || 0 }); } catch (error) { return crmErrorResponse(error, "Could not load employer contacts."); }
}

export async function POST(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; const body = await request.json().catch(() => ({})); const name = cleanText(body.full_name, 120); if (!name) return NextResponse.json({ error: "Contact name is required." }, { status: 400 }); const result = await context.client.from("employer_contacts").insert({ employer_user_id: context.workspaceOwnerId, full_name: name, work_email: cleanText(body.work_email, 180) || null, phone: cleanText(body.phone, 40) || null, job_title: cleanText(body.job_title, 120) || null, department: cleanText(body.department, 120) || null, contact_type: TYPES.has(body.contact_type) ? body.contact_type : "hiring_manager", notes: cleanText(body.notes, 2_000) || null, created_by: context.userId }).select(SELECT).single(); if (result.error) throw result.error; return NextResponse.json({ contact: result.data }, { status: 201 }); } catch (error) { return crmErrorResponse(error, "Could not create employer contact."); }
}

export async function PATCH(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; const body = await request.json().catch(() => ({})); if (!isUuid(body.contact_id)) return NextResponse.json({ error: "A valid contact is required." }, { status: 400 }); const updates: Record<string, unknown> = { updated_at: new Date().toISOString() }; if (body.full_name !== undefined) updates.full_name = cleanText(body.full_name, 120); if (body.status === "active" || body.status === "inactive") updates.status = body.status; if (body.job_title !== undefined) updates.job_title = cleanText(body.job_title, 120) || null; if (body.department !== undefined) updates.department = cleanText(body.department, 120) || null; const result = await context.client.from("employer_contacts").update(updates).eq("id", body.contact_id).eq("employer_user_id", context.workspaceOwnerId).select(SELECT).single(); if (result.error) throw result.error; return NextResponse.json({ contact: result.data }); } catch (error) { return crmErrorResponse(error, "Could not update employer contact."); }
}
