import { NextResponse } from "next/server";
import { cleanText, crmErrorResponse, crmRateResponse, enforceCrmWriteRate, isUuid, requireTalentCrmRequester } from "@/lib/crm/server";

const STATUSES = new Set(["submitted", "reviewing", "interviewing", "hired", "rejected", "withdrawn"]);
const SELECT = "id,employer_user_id,referrer_user_id,referrer_name,referrer_email,candidate_id,candidate_name,candidate_email,job_id,status,reward_amount,reward_status,notes,created_at,updated_at";

export async function GET(request: Request) {
  try { const context = await requireTalentCrmRequester(request); if ("response" in context) return context.response; const url = new URL(request.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1)); const limit = Math.max(1, Math.min(100, Number(url.searchParams.get("limit") || 25))); const from = (page - 1) * limit; const result = await context.client.from("employee_referrals").select(SELECT, { count: "exact" }).eq("employer_user_id", context.workspaceOwnerId).order("created_at", { ascending: false }).range(from, from + limit - 1); if (result.error) throw new Error(result.error.message); return NextResponse.json({ referrals: result.data || [], page, limit, total: result.count || 0 }); } catch (error) { return crmErrorResponse(error, "Could not load referrals."); }
}

export async function POST(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; if (!enforceCrmWriteRate(context.userId, "referrals", 30)) return crmRateResponse(); const body = await request.json().catch(() => ({})); const referrerName = cleanText(body.referrer_name, 120); const candidateName = cleanText(body.candidate_name, 120); if (!referrerName || !candidateName) return NextResponse.json({ error: "Referrer and candidate names are required." }, { status: 400 }); const result = await context.client.from("employee_referrals").insert({ employer_user_id: context.workspaceOwnerId, referrer_user_id: isUuid(body.referrer_user_id) ? body.referrer_user_id : null, referrer_name: referrerName, referrer_email: cleanText(body.referrer_email, 180) || null, candidate_id: isUuid(body.candidate_id) ? body.candidate_id : null, candidate_name: candidateName, candidate_email: cleanText(body.candidate_email, 180) || null, job_id: isUuid(body.job_id) ? body.job_id : null, notes: cleanText(body.notes, 2_000) || null }).select(SELECT).single(); if (result.error) throw new Error(result.error.message); await context.client.from("referral_history").insert({ referral_id: result.data.id, new_status: "submitted", note: "Referral submitted", changed_by: context.userId }); return NextResponse.json({ referral: result.data }, { status: 201 }); } catch (error) { return crmErrorResponse(error, "Could not submit referral."); }
}

export async function PATCH(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; const body = await request.json().catch(() => ({})); const status = cleanText(body.status, 30); if (!isUuid(body.referral_id) || !STATUSES.has(status)) return NextResponse.json({ error: "A valid referral and status are required." }, { status: 400 }); const existing = await context.client.from("employee_referrals").select("id,status").eq("id", body.referral_id).eq("employer_user_id", context.workspaceOwnerId).maybeSingle(); if (existing.error || !existing.data) return NextResponse.json({ error: "Referral was not found." }, { status: 404 }); const rewardAmount = body.reward_amount === undefined ? undefined : Math.max(0, Number(body.reward_amount) || 0); const result = await context.client.from("employee_referrals").update({ status, ...(rewardAmount !== undefined ? { reward_amount: rewardAmount } : {}), ...(body.reward_status ? { reward_status: cleanText(body.reward_status, 30) } : {}), updated_at: new Date().toISOString() }).eq("id", body.referral_id).select(SELECT).single(); if (result.error) throw new Error(result.error.message); await context.client.from("referral_history").insert({ referral_id: body.referral_id, previous_status: existing.data.status, new_status: status, note: cleanText(body.note, 1_000) || null, changed_by: context.userId }); return NextResponse.json({ referral: result.data }); } catch (error) { return crmErrorResponse(error, "Could not update referral."); }
}
