export const bdjobsDepartments = [
  "Accounting/Finance",
  "Agro (Plant/Animal/Fisheries)",
  "Bank/Non-Bank Fin. Institution",
  "Commercial/Supply Chain",
  "Company Secretary/Regulatory",
  "Customer Service/Call Centre",
  "Data Entry/Operator/BPO",
  "Design/Creative",
  "Education/Training",
  "Electrician/Electronics Technician",
  "Engineer/Architect",
  "Garments/Textile",
  "General Management/Admin",
  "Healthcare/Medical",
  "Hospitality/Travel/Tourism",
  "HR/Org. Development",
  "IT/Telecommunication",
  "Law/Legal",
  "Marketing/Sales",
  "Media/Advertisement/Event Management",
  "NGO/Development",
  "Pathologist/Lab Assistant",
  "Pharmaceutical",
  "Production/Operation",
  "Receptionist/PS",
  "Research/Consultancy",
  "Security/Support Service",
  "Security Guard",
  "Driver",
  "Chef/Cook",
  "Cleaner",
  "Nurse",
  "Peon",
  "Waiter/Waitress",
  "Delivery Man",
  "Sales Representative (SR)",
  "Showroom Assistant/Salesman",
  "Graphic Designer",
  "Caregiver/Nanny",
  "Garments Technician/Machine Operator",
  "CAD Operator",
  "Housekeeper",
  "Welder",
  "Plumber/Pipe Fitting",
  "Sewing Machine Operator",
  "Mason/Construction Worker",
  "Gym/Fitness Trainer",
  "Beautician/Salon Worker",
  "Gardener",
  "Interpreter",
  "Fire Safety/Firefighter",
  "Imam/Khatib/Muezzin",
  "Carpenter",
  "Physiotherapist",
  "Boiler Operator",
  "Others"
];
