export const bdjobsSkills = [
  "Accounting",
  "Accounts Payable",
  "Accounts Receivable",
  "Administration",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "After Sales Service",
  "Agriculture",
  "Android Development",
  "Angular",
  "Animation",
  "API Integration",
  "Architectural Design",
  "ASP.NET",
  "Asset Management",
  "Auditing",
  "AutoCAD",
  "AutoCAD 2D",
  "AutoCAD 3D",
  "Banking Operations",
  "Bash",
  "Billing",
  "Brand Management",
  "Budgeting",
  "Business Analysis",
  "Business Communication",
  "Business Development",
  "Call Center Operations",
  "Cash Management",
  "CCNA",
  "Civil Engineering",
  "Client Relationship Management",
  "Cloud Computing",
  "Communication",
  "Compliance",
  "Computer Hardware",
  "Construction Management",
  "Content Writing",
  "Coordination",
  "Corporate Sales",
  "Cost Control",
  "Credit Management",
  "CRM",
  "CSS",
  "Customer Care",
  "Customer Handling",
  "Customer Relationship Management",
  "Customer Service",
  "Data Analysis",
  "Data Entry",
  "Database Administration",
  "Database Management",
  "DevOps",
  "Digital Marketing",
  "Dispatch",
  "Documentation",
  "Driving",
  "E-commerce Operations",
  "Electrical Engineering",
  "Email Communication",
  "Employee Relations",
  "English Communication",
  "ERP",
  "Excel",
  "Express.js",
  "Facility Management",
  "Facebook Marketing",
  "Fashion Design",
  "Figma",
  "Financial Analysis",
  "Flutter",
  "Food Safety",
  "Frontend Development",
  "Garments Merchandising",
  "General Banking",
  "Git",
  "Google Ads",
  "Graphic Design",
  "HR Operations",
  "HTML",
  "Inventory Management",
  "iOS Development",
  "IT Support",
  "Java",
  "JavaScript",
  "KPI Reporting",
  "Laravel",
  "Lead Generation",
  "Leadership",
  "Legal Documentation",
  "Logistics",
  "Machine Learning",
  "Maintenance",
  "Market Research",
  "Marketing",
  "Mechanical Engineering",
  "Microsoft Office",
  "Mobile App Development",
  "MongoDB",
  "MS Word",
  "MySQL",
  "Negotiation",
  "Network Administration",
  "Network Security",
  "Next.js",
  "Node.js",
  "Office Management",
  "Operations Management",
  "Payroll",
  "PHP",
  "PostgreSQL",
  "Power BI",
  "Presentation",
  "Procurement",
  "Production Planning",
  "Project Management",
  "Python",
  "QA Testing",
  "Quality Assurance",
  "React",
  "React Native",
  "Recruitment",
  "Reporting",
  "Retail Sales",
  "Risk Management",
  "Sales",
  "Sales Forecasting",
  "SAP",
  "Scheduling",
  "Search Engine Optimization",
  "Security Operations",
  "Social Media Marketing",
  "Software Testing",
  "SQL",
  "Store Management",
  "Supply Chain",
  "Swift",
  "Tailwind CSS",
  "Tax",
  "Team Management",
  "Technical Support",
  "Telemarketing",
  "Time Management",
  "Training",
  "Troubleshooting",
  "TypeScript",
  "UI Design",
  "UI/UX Design",
  "Vendor Management",
  "Video Editing",
  "Vue.js",
  "Warehouse Management",
  "Web Development",
  "WordPress"
];
