"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarPlus, CheckCircle2, ClipboardCheck, FileText, Loader2, Send, StickyNote, X } from "lucide-react";
import { compactAuthHeaders } from "@/lib/compactAuthToken";
import type { PipelineCandidateDto, TimelineEventDto } from "@/types/ats";
import Badge from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Select from "@/components/ui/Select";

type Tab = "timeline" | "notes" | "tasks" | "interviews" | "assessments" | "offers";
type AnyRow = Record<string, any>;

async function atsRequest(path: string, init?: RequestInit) {
  const auth = await compactAuthHeaders("ats_workflow");
  const response = await fetch(path, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...auth, ...(init?.headers || {}) } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || "Workflow request failed.");
  return payload;
}

export default function ApplicationWorkflowDrawer({ candidate, onClose, onChanged }: { candidate: PipelineCandidateDto; onClose: () => void; onChanged: () => void }) {
  const [tab, setTab] = useState<Tab>("timeline"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [timeline, setTimeline] = useState<TimelineEventDto[]>([]); const [notes, setNotes] = useState<AnyRow[]>([]); const [tasks, setTasks] = useState<AnyRow[]>([]); const [interviews, setInterviews] = useState<AnyRow[]>([]); const [assessments, setAssessments] = useState<AnyRow[]>([]); const [offers, setOffers] = useState<AnyRow[]>([]);
  const [noteText, setNoteText] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [taskDue, setTaskDue] = useState(""); const [interviewType, setInterviewType] = useState("video"); const [interviewDate, setInterviewDate] = useState(""); const [assessmentTitle, setAssessmentTitle] = useState(""); const [offerTitle, setOfferTitle] = useState(""); const [offerSalary, setOfferSalary] = useState("");
  const [scorecard, setScorecard] = useState<Record<string, number>>({ communication: 3, technical: 3, leadership: 3, problem_solving: 3, culture_fit: 3, experience: 3, overall: 3 });
  const application = candidate.applicationId;
  const load = async () => {
    setLoading(true); setMessage("");
    try { const [time, note, task, interview, assessment, offer] = await Promise.all([atsRequest(`/api/timeline?application_id=${application}`), atsRequest(`/api/recruitment/notes?application_id=${application}`), atsRequest(`/api/tasks?application_id=${application}`), atsRequest(`/api/interviews?application_id=${application}`), atsRequest(`/api/assessments?application_id=${application}`), atsRequest(`/api/offers?application_id=${application}`)]); setTimeline(time.events || []); setNotes(note.notes || []); setTasks(task.tasks || []); setInterviews(interview.interviews || []); setAssessments(assessment.assessments || []); setOffers(offer.offers || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load workflow details."); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [application]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]);
  const completedTasks = useMemo(() => tasks.filter((task) => task.status === "completed").length, [tasks]);
  const submit = async (event: FormEvent, action: () => Promise<unknown>, clear: () => void) => { event.preventDefault(); setSaving(true); setMessage(""); try { await action(); clear(); await load(); onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save workflow item."); } finally { setSaving(false); } };
  const tabs: Array<[Tab, string]> = [["timeline", "Timeline"], ["notes", "Notes"], ["tasks", "Tasks"], ["interviews", "Interviews"], ["assessments", "Assessments"], ["offers", "Offers"]];
  return (
    <div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/30" role="dialog" aria-modal="true" aria-label={`${candidate.candidateName} recruitment workflow`}>
      <button className="absolute inset-0" onClick={onClose} aria-label="Close workflow details" />
      <aside className="relative flex h-full w-full max-w-2xl flex-col overflow-hidden bg-surface shadow-2xl dark:bg-slate-950">
        <header className="border-b border-border p-5 dark:border-white/10"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3">{candidate.candidatePhoto ? <img src={candidate.candidatePhoto} alt="" className="h-12 w-12 rounded-full object-cover" /> : <span className="grid h-12 w-12 place-items-center rounded-full bg-primary text-sm font-black text-white">{candidate.candidateName.slice(0, 2).toUpperCase()}</span>}<div className="min-w-0"><h2 className="truncate text-xl font-black text-text-main dark:text-white">{candidate.candidateName}</h2><p className="truncate text-sm font-semibold text-text-muted">{candidate.jobTitle}</p></div></div><button className="rounded-md p-2 text-text-muted hover:bg-primary/5 hover:text-primary" onClick={onClose} aria-label="Close"><X /></button></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="primary">{candidate.stageName}</Badge>{candidate.matchScore !== null ? <Badge variant="match-score">AI {candidate.matchScore}%</Badge> : null}<Badge>{completedTasks}/{tasks.length} tasks complete</Badge></div></header>
        <nav className="flex gap-1 overflow-x-auto border-b border-border px-4 py-2 dark:border-white/10" aria-label="Application workflow sections">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-md px-3 py-2 text-xs font-black ${tab === id ? "bg-primary text-white" : "text-text-muted hover:bg-primary/5 hover:text-primary"}`}>{label}</button>)}</nav>
        <div className="flex-1 overflow-y-auto p-5">{message ? <p className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700 dark:border-red-400/20 dark:bg-red-400/10 dark:text-red-200">{message}</p> : null}{loading ? <div className="grid min-h-60 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div> : <>
          {tab === "timeline" ? <List empty="No timeline events yet.">{timeline.map((item) => <article key={item.id} className="relative border-l-2 border-primary/30 pl-5"><span className="absolute -left-[7px] top-1 h-3 w-3 rounded-full bg-primary" /><h3 className="text-sm font-black text-text-main dark:text-white">{item.title}</h3><p className="mt-1 text-xs text-text-muted">{item.description || item.eventType.replaceAll("_", " ")}</p><p className="mt-2 text-[10px] font-bold uppercase text-text-muted">{item.actorName || "System"} - {new Date(item.createdAt).toLocaleString()}</p></article>)}</List> : null}
          {tab === "notes" ? <><Form title="Add private recruiter note" icon={StickyNote} onSubmit={(event) => submit(event, () => atsRequest("/api/recruitment/notes", { method: "POST", body: JSON.stringify({ application_id: application, plain_text: noteText }) }), () => setNoteText(""))}><textarea value={noteText} onChange={(event) => setNoteText(event.target.value)} required maxLength={10000} placeholder="Add context, @mentions, or interview observations..." className="min-h-28 w-full rounded-md border border-border bg-bg p-3 text-sm dark:border-white/10 dark:bg-white/5" /><Save disabled={saving || !noteText.trim()} /></Form><List empty="No private notes yet.">{notes.map((note) => <article key={note.id} className="rounded-md border border-border p-4 dark:border-white/10"><p className="whitespace-pre-wrap text-sm text-text-main dark:text-white">{note.plain_text}</p><p className="mt-3 text-[10px] font-bold uppercase text-text-muted">Version {note.current_version} - {new Date(note.updated_at).toLocaleString()}</p></article>)}</List></> : null}
          {tab === "tasks" ? <><Form title="Create task" icon={CheckCircle2} onSubmit={(event) => submit(event, () => atsRequest("/api/tasks", { method: "POST", body: JSON.stringify({ application_id: application, title: taskTitle, due_at: taskDue || null }) }), () => { setTaskTitle(""); setTaskDue(""); })}><Input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} required placeholder="Call candidate, review CV..." /><Input type="datetime-local" value={taskDue} onChange={(event) => setTaskDue(event.target.value)} /><Save disabled={saving || !taskTitle.trim()} /></Form><List empty="No tasks yet.">{tasks.map((task) => <article key={task.id} className="flex items-center justify-between gap-3 rounded-md border border-border p-4 dark:border-white/10"><div><h3 className="text-sm font-black text-text-main dark:text-white">{task.title}</h3><p className="mt-1 text-xs text-text-muted">{task.due_at ? new Date(task.due_at).toLocaleString() : "No due date"}</p></div><button disabled={task.status === "completed"} onClick={() => atsRequest("/api/tasks", { method: "PATCH", body: JSON.stringify({ task_id: task.id, status: "completed" }) }).then(load)} className="rounded-md border border-border px-3 py-2 text-xs font-black disabled:text-success dark:border-white/10">{task.status === "completed" ? "Completed" : task.status.replace("_", " ")}</button></article>)}</List></> : null}
          {tab === "interviews" ? <><Form title="Schedule interview" icon={CalendarPlus} onSubmit={(event) => submit(event, () => atsRequest("/api/interviews", { method: "POST", body: JSON.stringify({ application_id: application, interview_type: interviewType, scheduled_at: interviewDate }) }), () => setInterviewDate(""))}><Select value={interviewType} onChange={(event) => setInterviewType(event.target.value)}>{["phone", "video", "onsite", "panel", "technical", "hr", "final"].map((value) => <option key={value}>{value}</option>)}</Select><Input type="datetime-local" value={interviewDate} onChange={(event) => setInterviewDate(event.target.value)} required /><Save disabled={saving || !interviewDate} /></Form><List empty="No interviews scheduled.">{interviews.map((item) => <article key={item.id} className="rounded-md border border-border p-4 dark:border-white/10"><div className="flex justify-between gap-3"><h3 className="text-sm font-black capitalize text-text-main dark:text-white">{item.interview_type} interview</h3><Badge>{item.status}</Badge></div><p className="mt-2 text-xs text-text-muted">{new Date(item.scheduled_at).toLocaleString()} - {item.duration_minutes} minutes</p>{item.feedback_summary?.submissions ? <p className="mt-2 text-xs font-bold text-success">Consensus: {item.feedback_summary.averages.overall}/5 from {item.feedback_summary.submissions} scorecard{item.feedback_summary.submissions === 1 ? "" : "s"}</p> : null}{item.status === "scheduled" ? <Button variant="secondary" className="mt-3 px-3 py-1.5 text-xs" onClick={() => atsRequest("/api/interviews", { method: "PATCH", body: JSON.stringify({ interview_id: item.id, status: "completed" }) }).then(load)}>Mark completed</Button> : <details className="mt-3"><summary className="cursor-pointer text-xs font-black text-primary">Submit independent scorecard</summary><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.keys(scorecard).map((category) => <label key={category} className="text-[10px] font-black uppercase text-text-muted">{category.replace("_", " ")}<Input type="number" min="1" max="5" value={scorecard[category]} onChange={(event) => setScorecard((current) => ({ ...current, [category]: Number(event.target.value) }))} className="mt-1 py-2" /></label>)}</div><Button className="mt-3 w-full" onClick={() => atsRequest("/api/interviews", { method: "PATCH", body: JSON.stringify({ interview_id: item.id, action: "feedback", ...scorecard }) }).then(load)}>Submit scorecard</Button></details>}</article>)}</List></> : null}
          {tab === "assessments" ? <><Form title="Assign assessment" icon={ClipboardCheck} onSubmit={(event) => submit(event, () => atsRequest("/api/assessments", { method: "POST", body: JSON.stringify({ application_id: application, title: assessmentTitle }) }), () => setAssessmentTitle(""))}><Input value={assessmentTitle} onChange={(event) => setAssessmentTitle(event.target.value)} required placeholder="Technical exercise" /><Save disabled={saving || !assessmentTitle.trim()} /></Form><List empty="No assessments assigned.">{assessments.map((item) => <article key={item.id} className="flex justify-between gap-3 rounded-md border border-border p-4 dark:border-white/10"><div><h3 className="text-sm font-black text-text-main dark:text-white">{item.title}</h3><p className="text-xs text-text-muted">{item.provider}</p></div><Badge>{item.status}</Badge></article>)}</List></> : null}
          {tab === "offers" ? <><Form title="Create offer version" icon={FileText} onSubmit={(event) => submit(event, () => atsRequest("/api/offers", { method: "POST", body: JSON.stringify({ application_id: application, title: offerTitle, salary: offerSalary ? Number(offerSalary) : null }) }), () => { setOfferTitle(""); setOfferSalary(""); })}><Input value={offerTitle} onChange={(event) => setOfferTitle(event.target.value)} required placeholder="Employment offer" /><Input type="number" min="0" value={offerSalary} onChange={(event) => setOfferSalary(event.target.value)} placeholder="Salary (BDT)" /><Save disabled={saving || !offerTitle.trim()} /></Form><List empty="No offers created.">{offers.map((item) => <article key={item.id} className="rounded-md border border-border p-4 dark:border-white/10"><div className="flex justify-between gap-3"><h3 className="text-sm font-black text-text-main dark:text-white">Offer v{item.current_version}</h3><Badge>{item.status.replace("_", " ")}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{item.status === "draft" ? <Button className="px-3 py-1.5 text-xs" onClick={() => atsRequest("/api/offers", { method: "PATCH", body: JSON.stringify({ offer_id: item.id, status: "sent" }) }).then(load)}><Send className="h-3.5 w-3.5" />Send</Button> : null}{["sent", "viewed"].includes(item.status) ? <><Button variant="success" className="px-3 py-1.5 text-xs" onClick={() => atsRequest("/api/offers", { method: "PATCH", body: JSON.stringify({ offer_id: item.id, status: "accepted" }) }).then(load)}>Accept</Button><Button variant="secondary" className="px-3 py-1.5 text-xs" onClick={() => atsRequest("/api/offers", { method: "PATCH", body: JSON.stringify({ offer_id: item.id, status: "declined" }) }).then(load)}>Decline</Button></> : null}</div></article>)}</List></> : null}
        </>}</div>
      </aside>
    </div>
  );
}

function Form({ title, icon: Icon, onSubmit, children }: { title: string; icon: typeof StickyNote; onSubmit: (event: FormEvent) => void; children: React.ReactNode }) { return <form onSubmit={onSubmit} className="mb-5 space-y-3 rounded-lg border border-primary/20 bg-primary/5 p-4"><h3 className="flex items-center gap-2 text-sm font-black text-text-main dark:text-white"><Icon className="h-4 w-4 text-primary" />{title}</h3>{children}</form>; }
function Save({ disabled }: { disabled: boolean }) { return <Button type="submit" disabled={disabled} className="w-full">Save</Button>; }
function List({ empty, children }: { empty: string; children: React.ReactNode }) { return <div className="space-y-3">{Array.isArray(children) && children.length === 0 ? <p className="rounded-md border border-dashed border-border p-6 text-center text-sm font-bold text-text-muted dark:border-white/10">{empty}</p> : children}</div>; }
