"use client";

import { DragDropContext, Draggable, Droppable, type DropResult } from "@hello-pangea/dnd";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Archive, CheckSquare2, ChevronLeft, ChevronRight, Download, GripVertical, Loader2, Mail, Pencil, Plus, RotateCcw, Search, Tag, Trash2, UserCheck, X } from "lucide-react";
import { compactAuthHeaders } from "@/lib/compactAuthToken";
import { getProfileThumbnailUrl } from "@/lib/profileImageSync";
import { cn } from "@/lib/cn";
import { applyOptimisticStageMove } from "@/lib/ats/workflowEngine";
import { useAuth } from "@/hooks/useAuth";
import type { PipelineCandidateDto, PipelineDto, PipelineStageDto } from "@/types/ats";
import ApplicationWorkflowDrawer from "@/components/pipeline/ApplicationWorkflowDrawer";
import RecruiterDashboardMetrics from "@/components/pipeline/RecruiterDashboardMetrics";
import Badge from "@/components/ui/Badge";
import Card from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import EmptyState from "@/components/ui/EmptyState";
import Input from "@/components/ui/Input";
import Select from "@/components/ui/Select";
import Skeleton from "@/components/ui/Skeleton";

type UndoMove = { candidates: PipelineCandidateDto[]; targetStageId: string };

async function pipelineRequest(path: string, init?: RequestInit) {
  const auth = await compactAuthHeaders("ats_pipeline");
  const response = await fetch(path, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...auth, ...(init?.headers || {}) } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || "Recruitment pipeline request failed.");
  return payload;
}

function initials(name: string) { return name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "MX"; }

export default function PipelineBoard() {
  const { user } = useAuth();
  const [pipeline, setPipeline] = useState<PipelineDto | null>(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [stageFilter, setStageFilter] = useState(""); const [jobFilter, setJobFilter] = useState("");
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [activeCandidate, setActiveCandidate] = useState<PipelineCandidateDto | null>(null); const [undo, setUndo] = useState<UndoMove | null>(null); const [moving, setMoving] = useState(false); const [tagValue, setTagValue] = useState("");
  const loadMarker = useRef<HTMLDivElement>(null); const requestNumber = useRef(0);

  const loadPipeline = useCallback(async (page = 1, append = false) => {
    const requestId = ++requestNumber.current; if (append) setLoadingMore(true); else setLoading(true); setError("");
    try {
      const params = new URLSearchParams({ limit: "100", page: String(page) }); if (query.trim()) params.set("search", query.trim()); if (stageFilter) params.set("stage_id", stageFilter); if (jobFilter) params.set("job_id", jobFilter);
      const next = await pipelineRequest(`/api/pipeline?${params}`) as PipelineDto;
      if (requestId !== requestNumber.current) return;
      setPipeline((current) => append && current ? { ...next, candidates: Array.from(new Map([...current.candidates, ...next.candidates].map((item) => [item.applicationId, item])).values()) } : next);
    } catch (cause) { if (requestId === requestNumber.current) setError(cause instanceof Error ? cause.message : "Could not load the recruitment pipeline."); }
    finally { if (requestId === requestNumber.current) { setLoading(false); setLoadingMore(false); } }
  }, [jobFilter, query, stageFilter]);

  useEffect(() => { const timer = window.setTimeout(() => void loadPipeline(), query ? 300 : 0); return () => window.clearTimeout(timer); }, [loadPipeline, query]);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if (event.key === "/" && !/input|textarea|select/i.test((event.target as HTMLElement)?.tagName || "")) { event.preventDefault(); document.getElementById("ats-pipeline-search")?.focus(); } if (event.key === "Escape") { setSelected(new Set()); setActiveCandidate(null); } }; window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, []);
  useEffect(() => { const marker = loadMarker.current; if (!marker || !pipeline?.hasMore) return; const observer = new IntersectionObserver((entries) => { if (entries[0]?.isIntersecting && !loadingMore) void loadPipeline(Number(pipeline.nextCursor || 2), true); }, { rootMargin: "300px" }); observer.observe(marker); return () => observer.disconnect(); }, [loadPipeline, loadingMore, pipeline?.hasMore, pipeline?.nextCursor]);

  const activeStages = useMemo(() => pipeline?.stages.filter((stage) => !stage.isArchived) || [], [pipeline]);
  const jobs = useMemo(() => Array.from(new Map((pipeline?.candidates || []).map((candidate) => [candidate.jobId, candidate.jobTitle])).entries()), [pipeline]);
  const grouped = useMemo(() => { const map = new Map<string, PipelineCandidateDto[]>(); for (const stage of activeStages) map.set(stage.id, []); for (const candidate of pipeline?.candidates || []) if (map.has(candidate.stageId)) map.get(candidate.stageId)!.push(candidate); return map; }, [activeStages, pipeline?.candidates]);

  const moveCandidates = useCallback(async (applicationIds: string[], targetStageId: string, preserveUndo = false) => {
    if (!pipeline || !applicationIds.length) return; const target = pipeline.stages.find((stage) => stage.id === targetStageId); if (!target) return;
    const originals = pipeline.candidates.filter((candidate) => applicationIds.includes(candidate.applicationId)); if (!preserveUndo) setUndo({ candidates: originals, targetStageId });
    setMoving(true); setError(""); setPipeline((current) => current ? { ...current, candidates: applyOptimisticStageMove(current.candidates, applicationIds, target.id, target.name).map((candidate) => applicationIds.includes(candidate.applicationId) ? { ...candidate, stageEnteredAt: new Date().toISOString() } : candidate) } : current);
    try { await pipelineRequest("/api/pipeline/move", { method: "POST", body: JSON.stringify({ application_ids: applicationIds, stage_id: targetStageId, operation: "move" }) }); setSelected(new Set()); void loadPipeline(); }
    catch (cause) { setPipeline((current) => current ? { ...current, candidates: current.candidates.map((candidate) => originals.find((item) => item.applicationId === candidate.applicationId) || candidate) } : current); setUndo(null); setError(cause instanceof Error ? cause.message : "Could not move candidates."); }
    finally { setMoving(false); }
  }, [loadPipeline, pipeline]);

  const onDragEnd = (result: DropResult) => { if (!result.destination || result.destination.droppableId === result.source.droppableId) return; const ids = selected.has(result.draggableId) ? Array.from(selected) : [result.draggableId]; void moveCandidates(ids, result.destination.droppableId); };
  const undoMove = async () => { if (!undo) return; const groupedUndo = new Map<string, string[]>(); for (const candidate of undo.candidates) { const list = groupedUndo.get(candidate.stageId) || []; list.push(candidate.applicationId); groupedUndo.set(candidate.stageId, list); } setUndo(null); for (const [stageId, ids] of groupedUndo) await moveCandidates(ids, stageId, true); };
  const bulkOperation = async (operation: "assign" | "tag" | "archive" | "reject") => { if (!selected.size || !window.confirm(`${operation[0].toUpperCase()}${operation.slice(1)} ${selected.size} selected candidate${selected.size === 1 ? "" : "s"}?`)) return; setMoving(true); try { await pipelineRequest("/api/pipeline/move", { method: "POST", body: JSON.stringify({ operation, application_ids: Array.from(selected), recruiter_id: operation === "assign" ? user?.id : undefined, tag: operation === "tag" ? tagValue : undefined }) }); setTagValue(""); setSelected(new Set()); await loadPipeline(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Bulk action failed."); } finally { setMoving(false); } };
  const emailSelected = async () => { const subject = window.prompt("Email subject", "Your MXVL application update"); if (!subject) return; const message = window.prompt("Email message"); if (!message) return; setMoving(true); try { await pipelineRequest("/api/recruitment/communications", { method: "POST", body: JSON.stringify({ application_ids: Array.from(selected), communication_type: "email", subject, body: message }) }); setSelected(new Set()); await loadPipeline(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not record the email communication."); } finally { setMoving(false); } };
  const exportSelected = () => { const rows = (pipeline?.candidates || []).filter((candidate) => selected.has(candidate.applicationId)); const csv = [["Candidate", "Job", "Stage", "AI Match", "Recruiter", "Applied"], ...rows.map((item) => [item.candidateName, item.jobTitle, item.stageName, item.matchScore ?? "", item.recruiterName || "", item.applicationDate])].map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "mxvl-pipeline-export.csv"; link.click(); URL.revokeObjectURL(link.href); };
  const configureStage = async (action: "rename" | "archive" | "remove", stage: PipelineStageDto) => { const body: Record<string, unknown> = { action, stage_id: stage.id }; if (action === "rename") { const name = window.prompt("Stage name", stage.name); if (!name || name === stage.name) return; body.name = name; } if (action === "archive") body.archived = !stage.isArchived; if (action === "remove" && !window.confirm(`Remove ${stage.name}? This is allowed only when the stage is empty.`)) return; try { await pipelineRequest("/api/pipeline", { method: "PATCH", body: JSON.stringify(body) }); await loadPipeline(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update stage."); } };
  const reorderStage = async (stage: PipelineStageDto, direction: -1 | 1) => { const index = activeStages.findIndex((item) => item.id === stage.id); const target = index + direction; if (index < 0 || target < 0 || target >= activeStages.length) return; const ordered = [...activeStages]; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; setPipeline((current) => current ? { ...current, stages: ordered.map((item, position) => ({ ...item, position })) } : current); try { await pipelineRequest("/api/pipeline", { method: "PATCH", body: JSON.stringify({ action: "reorder", stage_id: stage.id, stage_ids: ordered.map((item) => item.id) }) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not reorder stages."); await loadPipeline(); } };
  const addStage = async () => { const name = window.prompt("New pipeline stage name"); if (!name) return; try { await pipelineRequest("/api/pipeline", { method: "PATCH", body: JSON.stringify({ action: "add", name }) }); await loadPipeline(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not add stage."); } };

  if (loading && !pipeline) return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-24 rounded-lg" />)}</div><div className="flex gap-4 overflow-hidden">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-96 min-w-72 rounded-lg" />)}</div></div>;
  if (!pipeline) return <EmptyState icon={<CheckSquare2 />} title="ATS pipeline unavailable" message={error || "Apply the enterprise recruitment workflow migration and refresh this page."} />;

  return (
    <DragDropContext onDragEnd={onDragEnd}>
      <RecruiterDashboardMetrics />
      <div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex flex-1 flex-col gap-2 sm:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-muted" /><Input id="ats-pipeline-search" value={query} onChange={(event) => setQuery(event.target.value)} className="pl-10" placeholder="Search candidates, jobs, recruiters...  /" /></div><Select value={jobFilter} onChange={(event) => setJobFilter(event.target.value)} className="sm:max-w-56"><option value="">All jobs</option>{jobs.map(([id, title]) => <option key={id} value={id}>{title}</option>)}</Select><Select value={stageFilter} onChange={(event) => setStageFilter(event.target.value)} className="sm:max-w-48"><option value="">All stages</option>{activeStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</Select></div>
        <Button variant="secondary" onClick={addStage}><Plus className="h-4 w-4" />Add stage</Button>
      </div>
      {error ? <div className="mb-4 flex items-start justify-between gap-3 rounded-md border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700 dark:border-red-400/20 dark:bg-red-400/10 dark:text-red-200"><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss error"><X className="h-4 w-4" /></button></div> : null}
      {selected.size ? <div className="sticky top-16 z-30 mb-4 flex flex-wrap items-center gap-2 rounded-lg border border-primary/20 bg-surface p-3 shadow-elevated dark:bg-slate-900"><Badge variant="primary">{selected.size} selected</Badge><Select className="max-w-48 py-2" defaultValue="" onChange={(event) => { if (event.target.value) void moveCandidates(Array.from(selected), event.target.value); event.target.value = ""; }}><option value="">Move stage...</option>{activeStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</Select><Button variant="secondary" className="px-3 py-2 text-xs" disabled={!user?.id || moving} onClick={() => bulkOperation("assign")}><UserCheck className="h-3.5 w-3.5" />Assign to me</Button><div className="flex"><Input className="w-32 rounded-r-none py-2 text-xs" value={tagValue} onChange={(event) => setTagValue(event.target.value)} placeholder="Tag" /><Button variant="secondary" className="rounded-l-none px-3 py-2" disabled={!tagValue} onClick={() => bulkOperation("tag")} aria-label="Add tag"><Tag className="h-3.5 w-3.5" /></Button></div><Button variant="secondary" className="px-3 py-2 text-xs" onClick={emailSelected}><Mail className="h-3.5 w-3.5" />Email</Button><Button variant="secondary" className="px-3 py-2 text-xs" onClick={exportSelected}><Download className="h-3.5 w-3.5" />Export</Button><Button variant="secondary" className="px-3 py-2 text-xs" onClick={() => bulkOperation("archive")}><Archive className="h-3.5 w-3.5" />Archive</Button><Button variant="secondary" className="px-3 py-2 text-xs" onClick={() => bulkOperation("reject")}><X className="h-3.5 w-3.5" />Reject</Button></div> : null}
      <div className="max-w-full overflow-x-auto overscroll-x-contain pb-4" aria-label="Recruitment pipeline Kanban">
        <div className="grid min-w-max auto-cols-[minmax(280px,320px)] grid-flow-col items-start gap-4">
          {activeStages.map((stage) => <Droppable droppableId={stage.id} key={stage.id}>{(provided, snapshot) => <section ref={provided.innerRef} {...provided.droppableProps} className={cn("flex max-h-[70vh] min-h-[420px] w-[300px] flex-col rounded-lg border bg-bg/70 transition dark:bg-white/[0.03]", snapshot.isDraggingOver ? "border-primary ring-4 ring-primary/10" : "border-border dark:border-white/10")}>
            <header className="sticky top-0 z-10 flex items-center justify-between gap-2 border-b border-border bg-surface/95 p-3 backdrop-blur dark:border-white/10 dark:bg-slate-950/95"><div className="min-w-0"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: stage.color }} /><h3 className="truncate text-sm font-black text-text-main dark:text-white">{stage.name}</h3></div><p className="mt-1 text-[10px] font-bold text-text-muted">{stage.candidateCount} candidate{stage.candidateCount === 1 ? "" : "s"}</p></div><div className="flex items-center"><button className="rounded p-1 text-text-muted hover:bg-primary/5 hover:text-primary disabled:opacity-30" disabled={activeStages[0]?.id === stage.id} onClick={() => reorderStage(stage, -1)} title="Move stage left" aria-label={`Move ${stage.name} left`}><ChevronLeft className="h-3.5 w-3.5" /></button><button className="rounded p-1 text-text-muted hover:bg-primary/5 hover:text-primary disabled:opacity-30" disabled={activeStages[activeStages.length - 1]?.id === stage.id} onClick={() => reorderStage(stage, 1)} title="Move stage right" aria-label={`Move ${stage.name} right`}><ChevronRight className="h-3.5 w-3.5" /></button><button className="rounded p-1.5 text-text-muted hover:bg-primary/5 hover:text-primary" onClick={() => configureStage("rename", stage)} title="Rename stage" aria-label={`Rename ${stage.name}`}><Pencil className="h-3.5 w-3.5" /></button><button className="rounded p-1.5 text-text-muted hover:bg-primary/5 hover:text-primary" onClick={() => configureStage("archive", stage)} title="Archive stage" aria-label={`Archive ${stage.name}`}><Archive className="h-3.5 w-3.5" /></button><button className="rounded p-1.5 text-text-muted hover:bg-red-50 hover:text-red-600" onClick={() => configureStage("remove", stage)} title="Remove empty stage" aria-label={`Remove ${stage.name}`}><Trash2 className="h-3.5 w-3.5" /></button></div></header>
            <div className="flex-1 space-y-3 overflow-y-auto p-3">{(grouped.get(stage.id) || []).map((candidate, index) => <Draggable draggableId={candidate.applicationId} index={index} key={candidate.applicationId}>{(dragProvided, dragSnapshot) => <article ref={dragProvided.innerRef} {...dragProvided.draggableProps} style={{ ...dragProvided.draggableProps.style, contentVisibility: "auto", containIntrinsicSize: "150px" }} className={cn("rounded-lg border border-border bg-surface p-3 shadow-sm transition dark:border-white/10 dark:bg-slate-900", dragSnapshot.isDragging && "rotate-1 border-primary shadow-elevated", selected.has(candidate.applicationId) && "border-primary ring-2 ring-primary/15")}>
              <div className="flex items-start gap-2"><button {...dragProvided.dragHandleProps} className="mt-1 text-text-muted" aria-label={`Drag ${candidate.candidateName}`}><GripVertical className="h-4 w-4" /></button><input type="checkbox" checked={selected.has(candidate.applicationId)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(candidate.applicationId)) next.delete(candidate.applicationId); else next.add(candidate.applicationId); return next; })} className="mt-1.5 accent-primary" aria-label={`Select ${candidate.candidateName}`} /><button className="min-w-0 flex-1 text-left" onClick={() => setActiveCandidate(candidate)}><div className="flex items-center gap-2">{candidate.candidatePhoto ? <img src={getProfileThumbnailUrl(candidate.candidatePhoto) || candidate.candidatePhoto} alt="" loading="lazy" className="h-9 w-9 rounded-full object-cover" /> : <span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-primary to-success text-[10px] font-black text-white">{initials(candidate.candidateName)}</span>}<div className="min-w-0"><h4 className="truncate text-sm font-black text-text-main dark:text-white">{candidate.candidateName}</h4><p className="truncate text-[11px] font-semibold text-text-muted">{candidate.jobTitle}</p></div></div><div className="mt-3 flex items-center justify-between gap-2">{candidate.matchScore !== null ? <Badge variant={candidate.matchScore >= 80 ? "match-score" : "primary"}>AI {candidate.matchScore}%</Badge> : <Badge>Not scored</Badge>}<span className="text-[9px] font-bold text-text-muted">{new Date(candidate.applicationDate).toLocaleDateString()}</span></div>{candidate.recruiterName || candidate.tags.length ? <div className="mt-2 flex flex-wrap gap-1">{candidate.recruiterName ? <Badge>{candidate.recruiterName}</Badge> : null}{candidate.tags.slice(0, 2).map((tagName) => <Badge key={tagName} variant="primary">{tagName}</Badge>)}</div> : null}</button></div>
            </article>}</Draggable>)}{provided.placeholder}{!(grouped.get(stage.id) || []).length ? <div className="grid min-h-32 place-items-center rounded-md border border-dashed border-border p-4 text-center text-xs font-bold text-text-muted dark:border-white/10">Drop candidates here</div> : null}</div>
          </section>}</Droppable>)}
        </div>
      </div>
      <div ref={loadMarker} className="grid min-h-10 place-items-center">{loadingMore ? <Loader2 className="h-5 w-5 animate-spin text-primary" /> : pipeline.hasMore ? <span className="text-xs font-bold text-text-muted">Scroll to load more applications</span> : null}</div>
      {undo ? <div className="fixed bottom-24 left-1/2 z-[90] flex -translate-x-1/2 items-center gap-3 rounded-lg bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-2xl"><span>Moved {undo.candidates.length} candidate{undo.candidates.length === 1 ? "" : "s"}</span><button className="flex items-center gap-1 text-blue-300" onClick={undoMove}><RotateCcw className="h-4 w-4" />Undo</button><button onClick={() => setUndo(null)} aria-label="Dismiss"><X className="h-4 w-4" /></button></div> : null}
      {activeCandidate ? <ApplicationWorkflowDrawer candidate={activeCandidate} onClose={() => setActiveCandidate(null)} onChanged={() => void loadPipeline()} /> : null}
      {moving ? <div className="pointer-events-none fixed inset-x-0 top-0 z-[120] h-1 overflow-hidden bg-primary/20"><div className="h-full w-1/3 animate-pulse bg-primary" /></div> : null}
    </DragDropContext>
  );
}
