import { NextResponse } from "next/server";
import { cleanText, crmErrorResponse, isUuid, requireTalentCrmRequester } from "@/lib/crm/server";
import { extractOfferVariables, renderOfferTemplate } from "@/lib/talentCrm";

const SELECT = "id,employer_user_id,name,title_template,body_template,variables,approval_steps,is_default,is_archived,current_version,created_at,updated_at";

export async function GET(request: Request) {
  try { const context = await requireTalentCrmRequester(request); if ("response" in context) return context.response; const url = new URL(request.url); const page = Math.max(1, Number(url.searchParams.get("page") || 1)); const limit = Math.max(1, Math.min(100, Number(url.searchParams.get("limit") || 25))); const from = (page - 1) * limit; const result = await context.client.from("offer_templates").select(SELECT, { count: "exact" }).eq("employer_user_id", context.workspaceOwnerId).eq("is_archived", false).order("updated_at", { ascending: false }).range(from, from + limit - 1); if (result.error) throw result.error; return NextResponse.json({ templates: result.data || [], page, limit, total: result.count || 0 }); } catch (error) { return crmErrorResponse(error, "Could not load offer templates."); }
}

export async function POST(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; const body = await request.json().catch(() => ({})); const name = cleanText(body.name, 120); const title = cleanText(body.title_template, 500); const content = cleanText(body.body_template, 20_000); if (!name || !title || !content) return NextResponse.json({ error: "Template name, title, and body are required." }, { status: 400 }); const variables = extractOfferVariables(title, content); const result = await context.client.from("offer_templates").insert({ employer_user_id: context.workspaceOwnerId, name, title_template: title, body_template: content, variables, approval_steps: Array.isArray(body.approval_steps) ? body.approval_steps.slice(0, 20) : [], is_default: Boolean(body.is_default), created_by: context.userId }).select(SELECT).single(); if (result.error) throw result.error; const version = await context.client.from("offer_template_versions").insert({ template_id: result.data.id, version: 1, title_template: title, body_template: content, variables, approval_steps: result.data.approval_steps, created_by: context.userId }); if (version.error) throw version.error; return NextResponse.json({ template: result.data }, { status: 201 }); } catch (error) { return crmErrorResponse(error, "Could not create offer template."); }
}

export async function PATCH(request: Request) {
  try { const context = await requireTalentCrmRequester(request, true); if ("response" in context) return context.response; const body = await request.json().catch(() => ({})); if (!isUuid(body.template_id)) return NextResponse.json({ error: "A valid template is required." }, { status: 400 }); const existing = await context.client.from("offer_templates").select(SELECT).eq("id", body.template_id).eq("employer_user_id", context.workspaceOwnerId).maybeSingle(); if (existing.error) throw existing.error; if (!existing.data) return NextResponse.json({ error: "Offer template was not found." }, { status: 404 }); if (body.action === "preview") return NextResponse.json({ title: renderOfferTemplate(existing.data.title_template, body.variables || {}), body: renderOfferTemplate(existing.data.body_template, body.variables || {}), unresolvedVariables: existing.data.variables.filter((key: string) => body.variables?.[key] === undefined) }); const title = cleanText(body.title_template, 500) || existing.data.title_template; const content = cleanText(body.body_template, 20_000) || existing.data.body_template; const versionNumber = Number(existing.data.current_version) + 1; const variables = extractOfferVariables(title, content); const result = await context.client.from("offer_templates").update({ name: cleanText(body.name, 120) || existing.data.name, title_template: title, body_template: content, variables, approval_steps: Array.isArray(body.approval_steps) ? body.approval_steps.slice(0, 20) : existing.data.approval_steps, current_version: versionNumber, is_archived: Boolean(body.is_archived), updated_at: new Date().toISOString() }).eq("id", body.template_id).select(SELECT).single(); if (result.error) throw result.error; const version = await context.client.from("offer_template_versions").insert({ template_id: body.template_id, version: versionNumber, title_template: title, body_template: content, variables, approval_steps: result.data.approval_steps, created_by: context.userId }); if (version.error) throw version.error; return NextResponse.json({ template: result.data }); } catch (error) { return crmErrorResponse(error, "Could not update offer template."); }
}
